---
- include: "{{ playbook_dir }}/config/tasks/set_storage_folder_permissions.yml"
  when: "app_is_backend is defined and app_is_backend|bool == true"

- include: "{{ playbook_dir }}/config/tasks/set_cache_folder_permissions.yml"
  when: "app_is_backend is defined and app_is_backend|bool == true"

- include: "{{ playbook_dir }}/config/tasks/symlink_storage_public.yml"

#- include: "{{ playbook_dir }}/config/tasks/symlink_uploads.yml"

- include: "{{ playbook_dir }}/config/tasks/optimize_pre.yml"
  when: "app_is_backend is defined and app_is_backend|bool == true"

- include: "{{ playbook_dir }}/config/tasks/self_diagnosis.yml"
  when: "app_run_self_diagnosis is defined and app_run_self_diagnosis|bool == true"
