---
- include: "{{ playbook_dir }}/config/tasks/set_writeable_permissions.yml"
  when: "app_set_writeable_permissions is defined and app_set_writeable_permissions|bool == true"

- include: "{{ playbook_dir }}/config/tasks/symlink_storage_public.yml"
  when: "app_symlink_storage_public is defined and app_symlink_storage_public|bool == true"

- include: "{{ playbook_dir }}/config/tasks/doctrine_prepare.yml"
  when: "app_doctrine_prepare is defined and app_doctrine_prepare|bool == true"

- include: "{{ playbook_dir }}/config/tasks/generate_passport_keys.yml"
  when: "app_generate_passport_keys is defined and app_generate_passport_keys|bool == true"

- include: "{{ playbook_dir }}/config/tasks/optimize_pre.yml"
  when: "app_optimize_pre is defined and app_optimize_pre|bool == true"

- include: "{{ playbook_dir }}/config/tasks/self_diagnosis.yml"
  when: "app_run_self_diagnosis is defined and app_run_self_diagnosis|bool == true"

- include: "{{ playbook_dir }}/config/tasks/doctrine_update.yml"
  when: "app_doctrine_update is defined and app_doctrine_update|bool == true"
