---
- include: "{{ playbook_dir }}/config/tasks/set_writeable_permissions.yml"
  when: "app_set_writeable_permissions is defined and app_set_writeable_permissions|bool == true"

- include: "{{ playbook_dir }}/config/tasks/symlink_storage_public.yml"
  when: "app_symlink_storage_public is defined and app_symlink_storage_public|bool == true"

- include: "{{ playbook_dir }}/config/tasks/optimize_pre.yml"
  when: "app_optimize_pre is defined and app_optimize_pre|bool == true"

- include: "{{ playbook_dir }}/config/tasks/self_diagnosis.yml"
  when: "app_run_self_diagnosis is defined and app_run_self_diagnosis|bool == true"
