---

- name: "APP | Deploy Supervisor configs for {{ app_project_name }}"
  become: true
  shell: "rsync -av --delete {{ app_current_path }}/build/deploy/supervisor/{{ app_environment }}/ /etc/supervisord.d"
  run_once: true
  delegate_to: "{{ inventory_hostname }}"
  tags:
    - app
    - post
