---

- name: "APP | Deploy Supervisor configs for {{ app_project_name }}"
  become: true
  synchronize:
    src: "{{ app_current_path }}/build/deploy/supervisor/{{ app_environment }}/"
    dest: "/etc/supervisord.d"
    delete: true
    become_user: "{{ ansible_user }}"
  run_once: true
#  delegate_to: "localhost"
  tags:
    - app
    - post
