---

- name: "APP | Deploy Supervisor configs for {{ app_project_name }}"
  synchronize:
    src: "{{ app_current_path }}/build/deploy/supervisor/{{ app_environment }}"
    dest: "/etc/supervisord.d"
    delete: true
  tags:
    - app
    - post
