---

## DEPRECATED: This task is deprecated and will be removed in a future release.

- name: "APP | Deploy Supervisor configs for {{ app_project_name }}"
  shell: "sudo rsync -av --delete {{ app_current_path }}/build/deploy/supervisor/{{ app_environment }}/ /etc/supervisord.d"
  run_once: true
  delegate_to: "{{ inventory_hostname }}"
  tags:
    - app
    - post
