---

- name: "APP | Recreate Config Cache"
  shell: "php artisan config:cache"
  args:
    chdir: "{{ ansistrano_release_path.stdout }}"
  tags:
    - app
    - pre

- name: "APP | Recreate Routes Cache"
  shell: "php artisan route:cache"
  args:
    chdir: "{{ ansistrano_release_path.stdout }}"
  tags:
    - app
    - pre

