---

- name: "APP | Recreate Config Cache"
  shell: "php artisan config:cache"
  args:
    chdir: "{{ ansistrano_release_path.stdout }}"
  tags:
    - app
    - pre

- name: "APP | Recreate Routes Cache"
  shell: "php artisan route:cache"
  args:
    chdir: "{{ ansistrano_release_path.stdout }}"
  when: "app_cmd_cache_routes is not defined"
  tags:
    - app
    - pre

- name: "APP | Recreate Custom Routes Cache"
  shell: "{{ app_cmd_cache_routes }}"
  args:
    chdir: "{{ ansistrano_release_path.stdout }}"
  when: "app_cmd_cache_routes is defined"
  tags:
    - app
    - pre

- name: "APP | Recreate Event Cache"
  shell: "php artisan event:cache"
  args:
    chdir: "{{ ansistrano_release_path.stdout }}"
  tags:
    - app
    - pre

