---

- name: "APP | Recreate Config Cache"
  shell: "php artisan config:cache"
  args:
    chdir: "{{ ansistrano_release_path.stdout }}"
  tags:
    - app
    - pre

- name: "APP | Recreate Routes Cache"
  shell: "{{ app_cmd_cache_routes | default('php artisan route:cache') }}"
  args:
    chdir: "{{ ansistrano_release_path.stdout }}"
  tags:
    - app
     - pre

- name: "APP | Recreate Event Cache"
  shell: "php artisan event:cache"
  args:
    chdir: "{{ ansistrano_release_path.stdout }}"
  tags:
    - app
    - pre

