---

- name: "APP | Restart Supervisor"
  become: true
  ansible.builtin.systemd:
    name: "{{ app_supervisor_service_name | default('supervisord') }}"
    state: restarted
  tags:
    - app
    - post
