---

- name: "APP | Set permissions to writeable paths"
  become: "{{ app_become_on_set_permissions | default(false) }}"
  shell: "chmod -R 777 {{ item }}"
  with_items: "{{ app_writeable_paths }}"
  args:
    chdir: "{{ ansistrano_release_path.stdout }}"
  tags:
    - app
    - pre
