---

- name: "APP | Set permissions to writeable paths"
  shell: "sudo chmod -R 777 {{ item }}"
  with_items: "{{ app_writeable_paths }}"
  args:
    chdir: "{{ ansistrano_release_path.stdout }}"
  tags:
    - app
    - pre
