---

- name: "APP | Dynamic | Create Nginx VHost Configuration"
  become: true
  register: nginx_configuration
  ansible.builtin.template:
    src: "{{ ansistrano_deploy_from }}/build/deploy/nginx/{{ app_environment }}.conf.j2"
    dest: "/etc/nginx/conf.d/{{ app_domain }}.conf"
    mode: "0644"
    backup: true
  when: app_dynamic_create_vhost is defined and app_dynamic_create_vhost|bool == true
  tags:
    - server
    - dynamic
    - pre

- name: "APP | Dynamic | Restart Nginx"
  become: true
  ansible.builtin.systemd:
    name: nginx
    state: restarted
  when: nginx_configuration.changed
  tags:
    - server
    - dynamic
    - pre
