---

- name: "APP | Dynamic | Configure Web Servers"
  become: true
  handlers:
    - name: RestartNginx
      ansible.builtin.systemd:
        name: nginx
        state: restarted
  tasks:
    - name: "APP | Dynamic | Create Nginx VHost Configuration"
      register: nginx_configuration
      ansible.builtin.template:
        src: "{{ app_current_path }}/build/deploy/templates/nginx-dynamic-vhost.conf.j2"
        dest: "/etc/nginx/conf.d/{{ app_domain }}.conf"
        mode: "0644"
        backup: true
      notify: RestartNginx
  when: app_dynamic_create_vhost is defined and app_dynamic_create_vhost|bool == true
  tags:
    - server
    - dynamic
    - pre
