---

- name: "APP | Dynamic | Create DNS Record via AWS Route53 API"
  delegate_to: localhost
  amazon.aws.route53:
    state: present
    zone: "{{ app_domain_name }}"
    record: "{{ app_domain }}"
    type: A
    ttl: 7200
    value: "{{ app_resolve_ips }}"
    overwrite: true
  run_once: true
  environment:
    AWS_ACCESS_KEY_ID: "{{ app_aws_access_key_id }}"
    AWS_SECRET_ACCESS_KEY: "{{ app_aws_secret_access_key }}"
  tags:
    - server
    - dynamic
    - pre
