---

- name: "APP | Dynamic | Remove Folder Structure"
  become: true
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  with_items:
    - "/var/www/{{ app_domain }}/app/releases"
    - "/var/www/{{ app_domain }}/api/releases"
    - "/var/www/{{ app_domain }}/api/shared/storage"
    - "/mnt/dynamic-deploy-{{ app_project_group | lower }}/{{ app_domain }}"
