---

- name: "APP | Dynamic | Remove SupervisorD Configuration"
  become: true
  ansible.builtin.file:
    path: "{{ app_supervisor_config_dest | default('/etc/supervisord.d') }}/{{ app_domain }}.{{ app_supervisor_config_ext | default('ini') }}"
    state: absent
